language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"
before_script:
  - npm install -g gulp bower
  - bower install --config.interactive=false
script: gulp
after_script: gulp coveralls